[package]
name = "binaries"
version = "0.1.0"
authors = ["chee <yay@chee.party>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
structopt = "0.3.16"
